[pytest]
testpaths = tests
base_url = https://www.saucedemo.com
addopts = -v --browser chromium --screenshot only-on-failure --tracing retain-on-failure --output test-results --html=reports/report.html --self-contained-html
